version: '3'
services:
  webapp:
    build: .
    container_name: mojesberna-webapp
    ports:
      - '8080:80'
    volumes:
      - ./src/:/src
    depends_on:
      - db
    env_file:
      - '.env'

  db:
    image: postgres:alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata/:/var/lib/postgresql/data/
    env_file:
      - 'container.env'

volumes:
  webapp:
  db: