"""Added relationship between materials and purchases tables

Revision ID: 01d46a8e493e
Revises: 340316ba80eb
Create Date: 2022-12-22 20:01:22.524440

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '01d46a8e493e'
down_revision = '340316ba80eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'materials', ['material_id'], ['material_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('material_id')

    # ### end Alembic commands ###
