"""Initial migration

Revision ID: 0af58c721a50
Revises: 
Create Date: 2022-12-22 18:06:42.670040

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0af58c721a50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=16), nullable=False),
                    sa.PrimaryKeyConstraint('role_id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('users',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(length=64), nullable=False),
                    sa.Column('last_name', sa.String(length=64), nullable=True),
                    sa.Column('telephone_number', sa.String(length=17), nullable=True),
                    sa.Column('password_hash', sa.String(length=128), nullable=False),
                    sa.PrimaryKeyConstraint('user_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
