"""Added relationship between users and roles tables

Revision ID: 156725678c10
Revises: 98f8bf08bc24
Create Date: 2022-12-22 19:39:46.889888

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '156725678c10'
down_revision = '98f8bf08bc24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['role_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
