"""address renamed to addresses

Revision ID: 19e1927d9e94
Revises: d24ae7da4fbc
Create Date: 2022-12-22 18:55:58.167771

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '19e1927d9e94'
down_revision = 'd24ae7da4fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
                    sa.Column('address_id', sa.Integer(), nullable=False),
                    sa.Column('city', sa.String(length=64), nullable=False),
                    sa.Column('street', sa.String(length=64), nullable=True),
                    sa.Column('house_number', sa.String(length=16), nullable=False),
                    sa.Column('zip_code', sa.String(length=16), nullable=False),
                    sa.PrimaryKeyConstraint('address_id')
                    )
    op.drop_table('address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
                    sa.Column('address_id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('city', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
                    sa.Column('street', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
                    sa.Column('house_number', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
                    sa.Column('zip_code', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('address_id', name='address_pkey')
                    )
    op.drop_table('addresses')
    # ### end Alembic commands ###
