"""Added relationship between users and addresses tables

Revision ID: 340316ba80eb
Revises: b8d45c7ceabe
Create Date: 2022-12-22 19:58:51.525204

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '340316ba80eb'
down_revision = 'b8d45c7ceabe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permanent_residence_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('temporary_residence_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'addresses', ['permanent_residence_id'], ['address_id'])
        batch_op.create_foreign_key(None, 'addresses', ['temporary_residence_id'], ['address_id'])
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('temporary_residence_id')
        batch_op.drop_column('permanent_residence_id')

    # ### end Alembic commands ###
