"""Implemented roles

Revision ID: 340cb674a440
Revises: 9425c8062717
Create Date: 2022-12-25 19:03:09.309874

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '340cb674a440'
down_revision = '9425c8062717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('default', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_roles_default'), ['default'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_default'))
        batch_op.drop_column('default')
        batch_op.drop_column('permissions')

    # ### end Alembic commands ###
