"""empty message

Revision ID: 529358c56c0e
Revises: 0af58c721a50
Create Date: 2022-12-22 18:15:15.183278

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '529358c56c0e'
down_revision = '0af58c721a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
