"""Added login attribute to users table

Revision ID: 739f9e902c90
Revises: 77300217c076
Create Date: 2022-12-23 19:11:13.548357

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '739f9e902c90'
down_revision = '77300217c076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login', sa.String(length=128), nullable=False))
        batch_op.create_unique_constraint(None, ['login'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('login')

    # ### end Alembic commands ###
