"""Added relationship between materials and price_list tables

Revision ID: 77300217c076
Revises: 01d46a8e493e
Create Date: 2022-12-22 20:04:41.716170

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '77300217c076'
down_revision = '01d46a8e493e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'materials', ['material_id'], ['material_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('material_id')

    # ### end Alembic commands ###
