"""Added purchases table

Revision ID: 8252c5622c48
Revises: 19e1927d9e94
Create Date: 2022-12-22 19:03:13.843842

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8252c5622c48'
down_revision = '19e1927d9e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchases',
                    sa.Column('purchase_id', sa.Integer(), nullable=False),
                    sa.Column('weight', sa.Float(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('purchase_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchases')
    # ### end Alembic commands ###
