"""Added price_list table

Revision ID: 98f8bf08bc24
Revises: a7f62225782f
Create Date: 2022-12-22 19:16:34.023372

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '98f8bf08bc24'
down_revision = 'a7f62225782f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_list',
                    sa.Column('price_id', sa.Integer(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('price_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_list')
    # ### end Alembic commands ###
