"""empty message

Revision ID: b64726fd3e86
Revises: 6e98719b5e48
Create Date: 2022-12-22 18:17:47.486207

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b64726fd3e86'
down_revision = '6e98719b5e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('first_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
                    sa.Column('last_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
                    sa.Column('telephone_number', sa.VARCHAR(length=17), autoincrement=False, nullable=True),
                    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('user_id', name='users_pkey')
                    )
    # ### end Alembic commands ###
