"""Added relationship between users and purchases tables

Revision ID: b8d45c7ceabe
Revises: 156725678c10
Create Date: 2022-12-22 19:50:27.784282

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b8d45c7ceabe'
down_revision = '156725678c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buying_employee_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('selling_customer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['selling_customer_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'users', ['buying_employee_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('selling_customer_id')
        batch_op.drop_column('buying_employee_id')

    # ### end Alembic commands ###
